General:
  debug: 0
HardCodedIntegrand:
  type: loop_induced_TriBoxTri
  supegraph_yaml_file: ./data/loop_induced_TriBoxTri.yaml
  q: [30.0, 0.0, 0.0, 0.0]
  h_function:
    function: poly_left_right_exponential # Options are poly_exponential, poly_left_right_exponential, exponential
    sigma: 5.
    power: 10
  threshold_CT_settings:
    enabled: true
    include_integrated_ct: true
    variable: R # for the local CT: options in this case are R and logR
    local_ct_sliver_width: null # Specify an f64 for a finite sliver width, otherwise leave Option to null
    integrated_ct_sliver_width: null # Specify an f64 for a finite sliver width, otherwise leave Option to null
    parameterization_center: [[0.0, 0.0, 0.0]]
    local_ct_h_function:
      function: exponential_ct # Options in this case is just exponential_ct
      sigma: 1.
      enabled_dampening: true
    integrated_ct_h_function:
      function: poly_left_right_exponential # Options are poly_exponential, poly_left_right_exponential, exponential
      sigma: 15.
      power: 0
# HardCodedIntegrand:
#    type: unit_volume
#    n_3d_momenta: 11
# HardCodedIntegrand:
#   type: h_function_test
#   h_function:
#     function: poly_left_right_exponential # Options are poly_exponential, exponential
#     sigma: 0.01
#     power: 12
Integrator:
  n_bins: 64
  min_samples_for_update: 1000
  n_start: 10000
  n_increase: 1000
  n_max: 100000000
  integrated_phase: real
  learning_rate: 1.5
  train_on_avg: false
  show_max_wgt_info: true
Kinematics:
  e_cm: 30.0
Parameterization:
  b: 1.0
  input_rescaling:
    - - - 0.0
        - 1.0
      - - 0.0
        - 1.0
      - - 0.0
        - 1.0
    - - - 0.0
        - 1.0
      - - 0.0
        - 1.0
      - - 0.0
        - 1.0
    - - - 0.0
        - 1.0
      - - 0.0
        - 1.0
      - - 0.0
        - 1.0
  mapping: linear
  mode: spherical # choices are cartesian, spherical, hyperspherical and hyperspherical_flat
  shifts:
    - - 1.0
      - 0.0
      - 0.0
      - 0.0
    - - 1.0
      - 0.0
      - 0.0
      - 0.0
    - - 1.0
      - 0.0
      - 0.0
      - 0.0
