General:
  debug: 0
HardCodedIntegrand:
  type: TriBoxTriCFFAS
  supergraph_yaml_file: ./data/TriBoxTri_as.yaml
  q: [100.0, 0.0, 0.0, 0.0]
  numerator: one #spatial_exponential_dummy # Options are "one", "spatial_exponential_dummy" and "physical"
  sampling_basis: [1, 4, 7] #[1, 3, 6] #[1, 6, 3] #[1, 4, 7] #[0, 4, 7] #[1, 3, 6]
  selected_sg_cff_term: 55 # e.g. 55 (most complicated) or null to enable all
  # | #0   (-0|+1       )
  # | #1   (-2|+3       )
  # | #2   (-0|+4|+6    )
  # | #3   (+1|-4|-5    )
  # | #4   (-2|+6|-7    )
  # | #5   (+3|-5|+7    )
  # | #6   (-5|+6       )
  # | #7   (-0|+3|+4|+7 )
  # | #8   (+1|-2|-4|-7 )
  #                          [0, 1,  2, 3, 4,  5, 6,  7, 8]
  # CFF term 55 has the following signature: [ 1, 1, -1, 1, 1,-1, 1,-1, 1]
  selected_sector_signature: [1, 0, -1, 1, 0, -1, 0, -1, 0] # [1, 1, 1, 1, 1, 1, 1, 1, 1] # e.g. [1,1,1,1,1,1,1,1,1] or null to enable all
  h_function:
    function: poly_left_right_exponential # Options are poly_exponential, poly_left_right_exponential, exponential
    sigma: 1. #20.
    power: 0 #10 # Typically best to set to 3*n_loops+1
  threshold_CT_settings:
    enabled: true
    include_integrated_ct: false
    compute_only_im_squared: false
    im_squared_through_local_ct_only: false
    include_amplitude_level_cts: true
    variable: R # for the local CT: options in this case are R and logR
    local_ct_sliver_width: 1.0 # Specify an f64 for a finite sliver width, otherwise leave Option to null
    integrated_ct_sliver_width: 1.0 # Specify an f64 for a finite sliver width, otherwise leave Option to null
    parameterization_center: [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]] # [[3., -5., 1.], [2., 7., -3.], [2., -4., -1.]] # [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]
    include_cts_solved_in_two_loop_space: true
    include_cts_solved_in_one_loop_subspace: false
    apply_original_event_selection_to_cts: true
    sectoring_settings:
      enabled: false
      sector_based_analysis: false
      anti_select_threshold_against_observable: true
      force_one_loop_ct_in_soft_sector: false
      always_solve_cts_in_all_amplitude_loop_indices: false
      correlate_event_sector_with_ct_sector: false
      accept_all: true
      apply_hard_coded_rules: false
      check_for_absent_e_surfaces_when_building_mc_factor: false
      mc_factor_power: 0.
      hard_coded_rules_file: null
    local_ct_h_function:
      function: exponential_ct # Options in this case is just exponential_ct
      sigma: 15.
      enabled_dampening: true
    integrated_ct_h_function:
      function: poly_left_right_exponential # Options are poly_exponential, poly_left_right_exponential, exponential
      sigma: 5.
      power: 0
Integrator:
  n_bins: 8
  min_samples_for_update: 10000
  n_start: 1000000
  n_increase: 0
  n_max: 100000000
  integrated_phase: real
  learning_rate: 1.5
  train_on_avg: false
  show_max_wgt_info: true
Kinematics:
  e_cm: 100.0
Parameterization:
  b: 1.0
  mapping: linear
  mode: spherical # choices are cartesian, spherical, hyperspherical and hyperspherical_flat
# Selectors: []
Selectors:
  - type: jet
    min_jets: 2
    max_jets: 2
    min_jpt: 10.0
    min_j1pt: 15.0
    max_j1pt: -1.
    dR: 0.7
    use_fastjet: true
Observables:
  - type: cross_section
  # - type: jet1pt
  #   x_min: 0.
  #   x_max: 100.
  #   dR: 0.7
  #   min_jpt: 5.
  #   n_bins: 100
  #   write_to_file: true
  #   filename: "observables/jet1_pt.HwU"
  #   use_fastjet: true
